### ISSUE TITLE
Not your problem, but still

### ISSUE THREAD

**Issue by Zedwill96** [karate/fuego-fighters#14] opened 2021-02-08 13:03 UTC
Fatal error in CLI.py when exiting game, not your problem but if you could help me figured out why, that be awesome.

**Comment by karate** [comment] 2021-02-08 16:34
You're referring to #13, which is not going to be merged,

I can't troubleshoot this. You've made so many changes that I can't even make it run in the first place.

**Closed as completed by karate** 2021-02-08 16:34 UTC

**Comment by Zedwill96** [comment] 2021-02-08 16:41
ok that's fine, either way, to run it with prython just run CLI.py with python

**Comment by karate** [comment] 2021-02-08 17:05
I haven't installed `pygame` globally, only inside the virtual environment, with `pip install -r requirements.txt`.
If I try to run `python CLI.py` I get the following error:
```
$ python CLI.py
Traceback (most recent call last):
  File "/.../fuego-fighters/CLI.py", line 1, in <module>
    from __init__ import main
  File "/.../fuego-fighters/__init__.py", line 4, in <module>
    import pygame
ModuleNotFoundError: No module named 'pygame'
```

Maybe it's not your fault after all.

**Comment by karate** [comment] 2021-02-08 17:09
I tried the latest commit  in #13 and I don't see any errors.

**Comment by Zedwill96** [comment] 2021-02-08 17:18
have you updated to the latest version of pygame in your venv? When i first tried to package it i got that error, i have to install the latest pygame to venv, by the way i use pycharm

**Comment by karate** [comment] 2021-02-08 18:32
I think the problem was that you had tracked the `venv` directory.
As i said, I tried the latest commit from PR #13 and it works.
There is no fatal error in `CLI.py` when exiting the game. This is a non-reproducible bug.

**Comment by Zedwill96** [comment] 2021-02-08 22:26
No i reproduced it serveral time, it's with the packaged files, something to do with the --noconsole option during packaging, i know how to work around it, thanks man
